spring:
  application:
    name: myblog-web
  datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://106.55.61.15:3306/bear?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
   username: root
   password: Wjxg_123
   type: com.alibaba.druid.pool.DruidDataSource


  #邮箱配置
  mail:
    host: smtp.163.com
    username: 13720192573@163.com
    password: DGGQXKJBKXMYFRXO
    default-encoding: UTF-8
    port: 587
    properties:
      mail:
      smtp:
      auth: true
      socketFactory:
      class: javax.net.ssl.SSLSocketFactory

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    database: 0
    host: 106.55.61.15
    port: 6379
    password: Wjxg_123

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    log-impl:  org.apache.ibatis.logging.slf4j.Slf4jImpl
  #    逻辑删除
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
server:
  port: 8090
  servlet:
    context-path: /blog
    session:
      cookie:
        domain: 127.0.0.1

#邮箱配置
alioss:
  endpoint: oss-cn-hangzhou.aliyuncs.com
  accessKeyId: LTAI4GGxUPBP8RgRyaRJD2Lr
  accessKeySecret: ggkoW5sfLN7sS4aNHiG7YEwsXzURQQ
  bucketName: xiaoshuaiblog

